# 1. THE SERVICE
apiVersion: v1
kind: Service
metadata:
  name: django-prod-service
spec:
  type: NodePort
  selector:
    app: book-shop # This MUST match the label in the Deployment below
  ports:
    - protocol: TCP
      port: 80          # Port inside the cluster
      targetPort: 80  # Port your Django app listens on
      nodePort: 30001   # THE DOOR NGINX TALKS TO
---
# 2. THE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2 # Running 2 copies for high availability
  selector:
    matchLabels:
      app: book-shop
  template:
    metadata:
      labels:
        app: book-shop
    spec:
      containers:
      - name: django-container
        image: <YOUR_ECR_URL>:latest # GitHub Actions will update this tag
        ports:
        - containerPort: 8000
        # Optional: Add resource limits for your 30GB EC2 instance
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"